[plugin]
repository = "https://github.com/ereti/MagitekClicker.git"
commit = "3ae0cbb27a035a48bc27d888f2403ce1f4e0c7ce"
owners = ["ereti"]
project_path = "MagitekClicker"
changelog = "Initial release"